#### Carica il tuo file di regole .ars
LbUser_VA_VRules = cyber9.ars       # <--- Cambiato da sicurezza.ars a cyber9.ars

#### Dove mandare il traffico dopo il controllo
LbUser_OutIp = 127.0.0.1
LbUser_OutPort = 5000              # <--- MANCAVA! Senza questo l'agente non sa dove sia Flask

#### Configurazione del "Vigile"
LbUser_ListenIp = 0.0.0.0     
LbUser_ListenPort = 32456

#### Codice Lisp e Moduli
LbUser_LspCode = cyber9.scm        
LbUser_VA_GetAllHTTP = true
LbUser_VA_LocalSH_on = true